AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Resources for Order Management
Resources:

  ##########################################
  # Order Processor IAM ROLE               #
  ##########################################

  swOrderManagementRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "orderManagementPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:

            # cloud watch
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "*"

            # event bus
          - Effect: "Allow"
            Action: "events:PutEvents"
            Resource: "arn:aws:events:*:*:event-bus/sw-event-bus"
            # Resource: "arn:aws:events:eu-central-1:460357271599:event-bus/sw-event-bus"
            #Resource: !GetAtt ServerlesspressoEventBus.Arn

            # config table
          - Effect: "Allow"
            Action:
              - "dynamodb:Get*"
              - "dynamodb:Update*"
              - "dynamodb:PutItem"
            Resource: "arn:aws:dynamodb:*:*:table/sw-config-table"
            #"arn:aws:dynamodb:eu-central-1:460357271599:table/sw-config-table"
            # Resource: !GetAtt ConfigTable.Arn

            # config table
          - Effect: "Allow"
            Action:
              - "dynamodb:Get*"
              - "dynamodb:Update*"
              - "dynamodb:PutItem"
            Resource: "arn:aws:dynamodb:*:*:table/sw-order-counter-table"
            #"arn:aws:dynamodb:eu-central-1:460357271599:table/sw-order-counter-table"
            # Resource: !GetAtt ConfigTable.Arn

            # order table
          - Effect: "Allow"
            Action:
              - "dynamodb:Get*"
              - "dynamodb:Query"
              - "dynamodb:Scan"
              - "dynamodb:Delete*"
              - "dynamodb:Update*"
              - "dynamodb:PutItem"
            Resource: "arn:aws:dynamodb:*:*:table/sw-order-table"
            #"arn:aws:dynamodb:eu-central-1:460357271599:table/sw-config-table"
            # Resource: !GetAtt ConfigTable.Arn

      Roles:
        - Ref: "swOrderManagementRole"
