Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1152
      Handler: de.openknowledge.workshop.cloud.serverless.lambda.GreetingHandler
      CodeUri: /Volumes/work/ok-community/training/cloud/serverless/serverless-coffee/serverless-workshop-trainer/05_testing/unit-testing
      Runtime: java11
      Architectures:
        - x86_64